# escape=`

FROM lacledeslan/gamesvr-dods

LABEL maintainer "Laclede's LAN <contact@lacledeslan.com>"

ENV IMAGE="gamesvr-dods-freeplay"

HEALTHCHECK NONE

COPY ./dist /app/dod/

COPY ./dist.linux /app/dod/

# UPDATE USERNAME
RUN usermod -l DODSFreeplay DODS

USER DODSFreeplay

WORKDIR /app/
